#ifndef JOB_TYPE_h
#define JOB_TYPE_h

typedef enum {
	UPDATE_GRAPH,
	ASK_CONSTRAINTS,
	ASK_CONSTRAINTS_WITH_SOURCE,
	ASK_CONSTRAINTS_WITH_TARGET,
	ASK_CONSTRAINTS_WITH_S_T,
	ANSWER_QUERY,
	ASK_PATH,
	QUIT,
} JobType;

#endif